### ISSUE TITLE
Investigate trie key prefix for constract storage

### ISSUE THREAD

**Issue by seunlanlege** [ComposableFi/nearcore#4]
Well we want to know if there's a determinstic trie key prefix for all contract storage items in the _global*_ state trie.

* near has shards so not sure if there's any global state trie, or shard sub-tries

**Comment by blasrodri** [comment]
@seunlanlege can you be more specific here when you say "deterministic"?
What kind of operation are you thinking, and what would be a non deterministic result in that context?

**Comment by seunlanlege** [comment]
Deterministic meaning, the key-path to the contract storage in the state trie never changes.

**Comment by blasrodri** [comment]
Is there a type of trie that's not deterministic?

**Comment by seunlanlege** [comment]
Like I said

> near has shards so not sure if there's any global state trie, or shard sub-tries

I'm thinking it's possible that contracts maybe called across shards, giving us a different key prefix each time. Which is why it needs investigating. We need to know near's execution model. 

Otherwise do contracts live permanently in a single shard?

**Comment by seunlanlege** [comment]
This seems to be required reading: 

https://near.org/papers/nightshade/

**Comment by blasrodri** [comment]
Thanks for the resource. 
Our interest is only in querying the storage of our own contract, right? From what I can see on the [SDK](https://docs.rs/near-sdk/latest/near_sdk/env/fn.storage_read.html) there's no key-prefix that's related to the shard at all.

From [the docs](https://nomicon.io/Architecture#trie)
> The blockchain layer manipulates the trie directly. It partitions the trie between the shards to distribute the load. It synchronizes the trie between the nodes, and eventually it is responsible for maintaining the consistency of the trie between the nodes through its consensus mechanism and other game-theoretic methods.

Is this sufficient proof of what you are thinking it could be a problem @seunlanlege ? I'm not sure I understand the use case. It would help if you could provide me with an example of the operation that we're looking to perform.

**Comment by seunlanlege** [comment]
I guess this means that there's a global trie-root. In that case, it simplifies things.
