### ISSUE TITLE
Investigate getting the shard state root into header proofs

### ISSUE THREAD

**Issue by seunlanlege** [ComposableFi/nearcore#5]
This is possibly already possible, just want us to have a reference point for the answer

**Comment by blasrodri** [comment]
@seunlanlege when you say shard state root, do you mean a specific shard?

**Comment by blasrodri** [comment]
We can get, given a block all chunks details
https://docs.near.org/api/rpc/block-chunk#block-details
https://github.com/near/nearcore/blob/master/nearcore/benches/store.rs#L40-L41

**Comment by seunlanlege** [comment]
Looks good then
