### ISSUE TITLE
State proofs of existence/non-existence

### ISSUE THREAD

**Issue by seunlanlege** [ComposableFi/nearcore#6]
Because of the requirements for [ics23](https://github.com/cosmos/ibc/blob/master/spec/core/ics-023-vector-commitments/README.md#proof-verification) we need near to support generating proofs of non-existence of contract state.

**Comment by blasrodri** [comment]
Currently being reviewed: https://github.com/near/nearcore/pull/7205
Missing proofs of non-existence

**Comment by blasrodri** [comment]
@vmarkushin

**Comment by seunlanlege** [comment]
Regardless of if this merged upstream, can we already use this to generate proofs from rpc?

**Comment by blasrodri** [comment]
> Regardless of if this merged upstream, can we already use this to generate proofs from rpc?

Not yet. Will work on it.
See my [comment](https://github.com/ComposableFi/near-trustless-bridge/pull/12#issuecomment-1210290656)

**Comment by seunlanlege** [comment]
Ok just checking in
