### ISSUE TITLE
Add host functions for verifying `parity/trie` proofs

### ISSUE THREAD

**Issue by seunlanlege** [ComposableFi/nearcore#7]
In order to verify ibc packet commitment proofs coming from our parachain, near needs to implement host functions to verify `parity/trie` proofs of existence and non-existence.

**Comment by seunlanlege** [comment]
Could be potentially rolled into one api: 

```rust
pub fn verify_parity_trie_proof<P, I>(root: H256, proof: &P, items: I) -> Result<(), Error>
    where
        P: IntoIterator<Item=Vec<u8>>,
        I: IntoIterator<Item=(Vec<u8>, Option<Vec<u8>>)> //(key, value)
{}
```

**Comment by blasrodri** [comment]
This one has been already added on our internal fork: https://github.com/ComposableFi/nearcore/pull/3/files#diff-8df9ae8ecbf1224f7f000dd60280838a7399a49e00af2754cc41f5a4b1ac2640R1211

However, we're running out of gas.

**Comment by seunlanlege** [comment]
After implementing this in wasm on our substrate chain, I think it's fine to implement this in wasm on near as well.

**Comment by blasrodri** [comment]
> After implementing this in wasm on our substrate chain, I think it's fine to implement this in wasm on near as well.

Will I get a wine?

**Comment by seunlanlege** [comment]
> Will I get a wine?

the near team technically didn't reject this so, no wine 🥲
