### ISSUE TITLE
Obtain batch transaction proofs

### ISSUE THREAD

**Issue by seunlanlege** [ComposableFi/nearcore#8]
We can leverage smaller merkle proof sizes by simply batching up txs, (in this case, `ConsensusState`-s) generated by near before submitting them to `pallet-ibc`.

**Comment by blasrodri** [comment]
@vmarkushin was suggesting a crate. I'm not sure how it will work with NEAR's internal structure (shards, etc). I think this one needs some whiteboarding.

**Comment by seunlanlege** [comment]
Let's set up a white boarding call

**Comment by blasrodri** [comment]
This one is waiting for review here: https://github.com/ComposableFi/near-trustless-bridge/pull/12
